services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'habitos_ninos'
    volumes:
      - ./habitos_ninos.sql:/docker-entrypoint-initdb.d/habitos_ninos.sql
    ports:
      - "3307:3306"

  pythonapp:
    build: ./app
    depends_on:
      - mysql
    ports:
      - "4001:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
